version: "3"
services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: yoginth
      POSTGRES_PASSWORD: ygsgmane2
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
